openapi: '3.0.3'
info:
  title: Flirtini Accounts API
  description: API for managing Flirtini accounts
  version: '1.0'
  contact:
    name: Flirtini Team
servers:
  - url: http://172.24.3.162:3000
    description: Server
tags:
  - name: Account
    description: Operations related to user accounts
paths:
  /account/login:
    post:
      operationId: loginUser
      description: Login a user
      tags:
        - Account
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
          content:
            text/plain:
              schema:
                type: string
  /account/logout:
    post:
      operationId: logoutUser
      tags:
        - Account
      description: Logout a user
      summary: Logout a user
      responses:
        '302':
          description: Redirect to login page

  /account/register:
    post:
      operationId: registerUser
      tags:
        - Account 
      description: Register a new user
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: Register success
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Username and password required
          content:
            text/plain:
              schema:
                type: string
        '409':
          description: Username already exists
          content:
            text/plain:
              schema:
                type: string